# Generated by Django 6.0.2 on 2026-02-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_visitante', '0002_registrovisitante_reset_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrovisitante',
            old_name='reset_token_expires',
            new_name='last_login',
        ),
        migrations.RemoveField(
            model_name='registrovisitante',
            name='reset_token',
        ),
    ]
