# Generated by Django 6.0.2 on 2026-02-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_visitante', '0003_rename_reset_token_expires_registrovisitante_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovisitante',
            name='rol',
            field=models.CharField(choices=[('interno', 'Usuario Interno (SENA)'), ('externo', 'Usuario Externo')], default='interno', max_length=10),
        ),
    ]
