# Generated by Django 6.0.2 on 2026-02-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_visitante', '0004_registrovisitante_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovisitante',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registrovisitante',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registrovisitante',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='registrovisitante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía (CC)'), ('CE', 'Cédula de Extranjería (CE)'), ('TI', 'Tarjeta de Identidad (TI)'), ('PA', 'Pasaporte (PA)'), ('PE', 'Permiso Especial (PE)')], default='CC', max_length=2),
        ),
    ]
