# Generated by Django 6.0.2 on 2026-02-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_visitante', '0004_registrovisitante_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrovisitante',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=100),
        ),
        migrations.AddField(
            model_name='registrovisitante',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100),
        ),
        migrations.AddField(
            model_name='registrovisitante',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='registrovisitante',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil')], default='CC', max_length=2),
        ),
    ]
