# Generated by Django 6.0.3 on 2026-03-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_visitante', '0005_registrovisitante_apellido_registrovisitante_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrovisitante',
            table='registro_visitante',
        ),
    ]
