# Generated by Django 6.0.3 on 2026-03-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documento_table_and_more'),
        ('documentos', '0003_alter_documentosubidoasistente_archivo'),
    ]

    operations = [
    ]
