# Generated by Django 6.0.2 on 2026-02-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0002_availability_end_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date', 'time', 'end_time']},
        ),
    ]
