# Generated by Django 6.0.2 on 2026-02-25 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0003_alter_availability_options'),
        ('visitaExterna', '0011_visitaexterna_fecha_visita_visitaexterna_hora_fin_and_more'),
        ('visitaInterna', '0013_visitainterna_fecha_visita_visitainterna_hora_fin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la visita')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('confirmada', 'Confirmada')], default='pendiente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visita_externa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_horario', to='visitaExterna.visitaexterna')),
                ('visita_interna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_horario', to='visitaInterna.visitainterna')),
            ],
            options={
                'verbose_name': 'Reserva de Horario',
                'verbose_name_plural': 'Reservas de Horarios',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
