# Generated by Django 6.0.3 on 2026-03-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0004_reservahorario'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='availability',
            table='availability',
        ),
        migrations.AlterModelTable(
            name='reservahorario',
            table='reserva_horario',
        ),
    ]
