"""
Django settings for MINEGATE_SENA project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-vif0ubxpndcm%r5-*3y_7m+x0jowu@g#s!z*!bl-44(-xwof*z"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'bootstrap5',
    'usuarios',
    'visitaInterna',
    'visitaExterna',
    'calendario',
    'accessibility',
    'gestion_visitas',
    'panel_visitante',
    'documentos',
    'panel_instructor_interno',
    'panel_instructor_externo',
    'coordinador',
    'reportes',
    'chatbot',
    'control_acceso_mina',
    'django_recaptcha',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "MINEGATE_SENA.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "Templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "MINEGATE_SENA.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sicam_db',
        'USER': 'sicam_user',
        'PASSWORD': 'Sicam123.',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# Ruta opcional para binarios de PostgreSQL (pg_dump/pg_restore).
# Si no se define, los comandos intentan resolver por PATH y rutas tipicas de Windows.
POSTGRES_BIN_DIR = os.getenv("POSTGRES_BIN_DIR", "")


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-co"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Para producción (cuando uses collectstatic)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# LOGIN/LOGOUT SETTINGS

# URLs de redirección después de login/logout
LOGIN_URL = "usuarios:login"  # A dónde ir si no está autenticado
LOGIN_REDIRECT_URL = "core:dashboard"  # A dónde ir después de login exitoso
LOGOUT_REDIRECT_URL = "/auth/login/"  # A dónde ir después de logout


# EMAIL CONFIGURATION
# Para desarrollo, usar Console Email Backend (muestra correos en consola)
# Para producción, cambiar a SMTP Real

# Configuración de correo para DESARROLLO (muestra en consola)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configuración de correo para PRODUCCIÓN (descomenta cuando sea necesario)
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # o tu proveedor de correo
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'tu-correo@gmail.com'
# EMAIL_HOST_PASSWORD = 'tu-contraseña-aplicación'
# DEFAULT_FROM_EMAIL = 'tu-correo@gmail.com'


# Para producción, descomentar y configurar:
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # O tu servidor SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "sicamsenacentrominero@gmail.com"
EMAIL_HOST_PASSWORD = "otui dscc tneu mgqc"
DEFAULT_FROM_EMAIL = "SICAM SENA CENTRO MINERO <sicamsenacentrominero@gmail.com>"

# Configuración de sesiones
SESSION_COOKIE_AGE = 3600  # 1 hora en segundos
SESSION_SAVE_EVERY_REQUEST = True  # Actualiza la sesión en cada request
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # La sesión persiste al cerrar navegador

# Configuración de seguridad de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 8,  # Mínimo 8 caracteres
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Configuración de marcos (iframes)
X_FRAME_OPTIONS = 'SAMEORIGIN'

# reCAPTCHA (usar variables de entorno en produccion)
RECAPTCHA_PUBLIC_KEY = os.getenv(
    "RECAPTCHA_PUBLIC_KEY",
    "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI",
)
RECAPTCHA_PRIVATE_KEY = os.getenv(
    "RECAPTCHA_PRIVATE_KEY",
    "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe",
)

if (
    RECAPTCHA_PUBLIC_KEY == "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
    and RECAPTCHA_PRIVATE_KEY == "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
):
    SILENCED_SYSTEM_CHECKS = ["django_recaptcha.recaptcha_test_key_error"]


CSRF_TRUSTED_ORIGINS = [
    "https://randall-nival-fredda.ngrok-free.dev"
]