# Generated by Django 6.0.2 on 2026-02-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_instructor_interno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PPT', 'Permiso Especial de Permanencia'), ('PP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('retirado', 'Retirado')], default='activo', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprendices', to='panel_instructor_interno.ficha', verbose_name='Ficha')),
            ],
            options={
                'verbose_name': 'Aprendiz',
                'verbose_name_plural': 'Aprendices',
                'ordering': ['apellido', 'nombre'],
                'unique_together': {('ficha', 'numero_documento')},
            },
        ),
    ]
