# Generated by Django 6.0.2 on 2026-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_instructor_interno', '0002_aprendiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='documento_adicional',
            field=models.FileField(blank=True, help_text='PDF o imagen de documento adicional', null=True, upload_to='aprendices/documentos/%Y/%m/', verbose_name='Documento Adicional (Opcional)'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='documento_identidad',
            field=models.FileField(blank=True, help_text='PDF o imagen del documento de identidad', null=True, upload_to='aprendices/documentos/%Y/%m/', verbose_name='Documento de Identidad (PDF/Imagen)'),
        ),
    ]
