# Generated by Django 6.0.2 on 2026-03-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_instructor_interno', '0003_aprendiz_documento_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='numero_documento',
            field=models.CharField(max_length=10, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
