# Generated by Django 6.0.3 on 2026-03-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_instructor_interno', '0004_alter_aprendiz_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to='aprendices/documentos/%Y/%m/'),
        ),
    ]
