# Generated by Django 6.0.3 on 2026-03-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_instructor_interno', '0004_alter_aprendiz_table_alter_ficha_table_and_more'),
        ('panel_instructor_interno', '0005_alter_aprendiz_documento_identidad'),
    ]

    operations = [
    ]
