# Generated by Django 6.0.2 on 2026-03-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_instructor_interno', '0007_merge_20260312_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='aprendiz',
            name='estado_doc',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Documentos aprobados'), ('rechazado', 'Documentos rechazados')], default='pendiente', max_length=20, verbose_name='Estado de Documentos'),
        ),
        migrations.AddField(
            model_name='aprendiz',
            name='observaciones_doc',
            field=models.TextField(blank=True, help_text='Observaciones del revisor sobre los documentos del aprendiz', null=True, verbose_name='Observaciones sobre Documentos'),
        ),
    ]
