# Generated by Django 6.0.3 on 2026-03-12 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_instructor_interno', '0008_aprendiz_estado_doc_aprendiz_observaciones_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='cantidad_aprendices',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Cantidad de Aprendices'),
        ),
        migrations.AlterField(
            model_name='programa',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
