# Generated by Django 6.0.3 on 2026-03-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel_instructor_interno', '0010_alter_ficha_cantidad_aprendices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono'),
        ),
    ]
