# Generated by Django 5.2.1 on 2026-03-04 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContenidoPaginaInformativa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo_principal", models.CharField(default="Centro Minero de Morcá", max_length=200)),
                (
                    "texto_principal",
                    models.TextField(default="Agenda tu experiencia minera de forma fácil, segura y digital."),
                ),
                (
                    "imagen_principal",
                    models.ImageField(blank=True, null=True, upload_to="pagina_informativa/hero/"),
                ),
                (
                    "texto_secundario",
                    models.TextField(default="Ven, visita el SENA y vive la minería como una experiencia de aprendizaje."),
                ),
                (
                    "imagen_secundaria",
                    models.ImageField(blank=True, null=True, upload_to="pagina_informativa/hero/"),
                ),
                (
                    "texto_descripcion",
                    models.TextField(
                        default="El SENA Centro Minero de Morcá, a través de la plataforma SICAM, ofrece un sistema digital para la gestión y programación de visitas a la mina didáctica."
                    ),
                ),
                (
                    "imagen_terciaria",
                    models.ImageField(blank=True, null=True, upload_to="pagina_informativa/hero/"),
                ),
                (
                    "titulo_galeria",
                    models.CharField(default="Explora Nuestras Instalaciones", max_length=200),
                ),
                (
                    "descripcion_galeria",
                    models.TextField(default="Conoce la mina didáctica y las experiencias que viven nuestros aprendices."),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Contenido de página informativa",
                "verbose_name_plural": "Contenido de página informativa",
            },
        ),
        migrations.CreateModel(
            name="ElementoGaleriaInformativa",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("imagen", "Imagen"), ("video", "Video")],
                        default="imagen",
                        max_length=10,
                    ),
                ),
                ("archivo", models.FileField(upload_to="pagina_informativa/galeria/")),
                ("titulo", models.CharField(max_length=120)),
                ("descripcion", models.CharField(blank=True, max_length=255)),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Elemento de galería informativa",
                "verbose_name_plural": "Elementos de galería informativa",
                "ordering": ["orden", "id"],
            },
        ),
    ]
