# Generated by Django 5.2.1 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementoEncabezadoInformativo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("texto", models.TextField(blank=True)),
                ("imagen", models.ImageField(upload_to="pagina_informativa/hero/")),
                ("orden", models.PositiveIntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Elemento de encabezado informativo",
                "verbose_name_plural": "Elementos de encabezado informativo",
                "ordering": ["orden", "id"],
            },
        ),
    ]
