# Generated by Django 6.0.3 on 2026-03-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mover_rutas_img_copia_a_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contenidopaginainformativa',
            table='contenido_pagina_informativa',
        ),
        migrations.AlterModelTable(
            name='elementoencabezadoinformativo',
            table='elemento_encabezado_informativo',
        ),
        migrations.AlterModelTable(
            name='elementogaleriainformativa',
            table='elemento_galeria_informativa',
        ),
    ]
