# Generated by Django 6.0.3 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_contenidopaginainformativa_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionBackupAutomatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('frecuencia', models.CharField(choices=[('6h', 'Cada 6 horas'), ('12h', 'Cada 12 horas'), ('24h', 'Cada 24 horas'), ('48h', 'Cada 48 horas'), ('72h', 'Cada 72 horas'), ('168h', 'Cada 7 días')], default='24h', max_length=5)),
                ('ultima_ejecucion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de backup automático',
                'verbose_name_plural': 'Configuración de backups automáticos',
                'db_table': 'configuracion_backup_automatico',
            },
        ),
    ]
