# Generated by Django 6.0.3 on 2026-03-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_instructor_interno', '0003_aprendiz_documento_adicional_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aprendiz',
            table='aprendiz',
        ),
        migrations.AlterModelTable(
            name='ficha',
            table='ficha',
        ),
        migrations.AlterModelTable(
            name='programa',
            table='programa',
        ),
    ]
