# Generated by Django 6.0.2 on 2026-02-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0013_visitainterna_fecha_visita_visitainterna_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='email_qr_enviado',
            field=models.BooleanField(default=False, verbose_name='Email con QR Enviado'),
        ),
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='fecha_envio_qr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío del QR'),
        ),
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='qr_generado',
            field=models.BooleanField(default=False, verbose_name='QR Generado'),
        ),
    ]
