# Generated by Django 6.0.3 on 2026-03-09 21:03

import visitaInterna.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0015_asistentevisitainterna_es_reutilizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='formato_autorizacion_padres',
            field=models.FileField(blank=True, null=True, upload_to=visitaInterna.models.documento_asistente_path_interna, verbose_name='Formato Autorización Padres de Familia (Requerido para menores de edad)'),
        ),
    ]
