# Generated by Django 6.0.2 on 2026-03-12 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0019_merge_20260311_0853'),
        ('visitaInterna', '0019_merge_20260311_1040'),
    ]

    operations = [
    ]
