# Generated by Django 4.2.27 on 2026-03-04 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAccesoMina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(db_index=True, max_length=50, verbose_name='Documento')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('categoria', models.CharField(help_text="Ej: 'Ficha: 12345' o 'Visitante Externo'", max_length=100, verbose_name='Categoría')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=7, verbose_name='Tipo de Movimiento')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de Acceso a la Mina',
                'verbose_name_plural': 'Registros de Acceso a la Mina',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
