# Generated by Django 6.0.3 on 2026-03-05 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AprobacionRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visita_id", models.IntegerField()),
                (
                    "visita_tipo",
                    models.CharField(
                        choices=[("interna", "Interna"), ("externa", "Externa")],
                        max_length=10,
                    ),
                ),
                ("responsable", models.CharField(max_length=255)),
                (
                    "institucion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("correo", models.CharField(blank=True, max_length=255, null=True)),
                ("cantidad", models.IntegerField(blank=True, null=True)),
                ("fecha_aprobacion", models.DateTimeField(auto_now_add=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_aprobacion"],
            },
        ),
    ]
