# Generated by Django 6.0.3 on 2026-03-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0013_asistentevisitaexterna_es_reutilizado_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asistentevisitaexterna',
            table='asistente_visita_externa',
        ),
        migrations.AlterModelTable(
            name='historialaccionvisitaexterna',
            table='historial_accion_visita_externa',
        ),
        migrations.AlterModelTable(
            name='visitaexterna',
            table='visita_externa',
        ),
    ]
