# Generated by Django 4.2.27 on 2026-01-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='aprobado',
            field=models.BooleanField(default=False, help_text='El usuario solo puede acceder al sistema si está aprobado por el administrador'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se aprobó el acceso del usuario', null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='razon_rechazo',
            field=models.TextField(blank=True, help_text='Razón por la cual se rechazó el acceso del usuario', null=True),
        ),
    ]
