# Generated by Django 4.2.27 on 2026-01-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitaInterna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Visita Interna',
                'verbose_name_plural': 'Visitas Internas',
                'ordering': ['-fecha'],
            },
        ),
    ]
