# Generated by Django 4.2.27 on 2026-02-02 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitainterna',
            options={'ordering': ['-id'], 'verbose_name': 'Visita Interna', 'verbose_name_plural': 'Visitas Internas'},
        ),
        migrations.RemoveField(
            model_name='visitainterna',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='visitainterna',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='visitainterna',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='visitainterna',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='visitainterna',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='visitainterna',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='visitainterna',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='visitainterna',
            name='cantidad_aprendices',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad de aprendices'),
        ),
        migrations.AddField(
            model_name='visitainterna',
            name='correo_responsable',
            field=models.EmailField(default='', max_length=254, verbose_name='Correo del responsable'),
        ),
        migrations.AddField(
            model_name='visitainterna',
            name='documento_responsable',
            field=models.CharField(default='', max_length=50, verbose_name='Documento del responsable'),
        ),
        migrations.AddField(
            model_name='visitainterna',
            name='nombre_ficha',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre de Ficha'),
        ),
        migrations.AddField(
            model_name='visitainterna',
            name='numero_ficha',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Ficha'),
        ),
        migrations.AddField(
            model_name='visitainterna',
            name='telefono_responsable',
            field=models.CharField(default='', max_length=20, verbose_name='Teléfono del responsable'),
        ),
    ]
