# Generated by Django 4.2.27 on 2026-02-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0003_alter_visitainterna_cantidad_aprendices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitainterna',
            name='nombre_ficha',
        ),
        migrations.AddField(
            model_name='visitainterna',
            name='nombre_programa',
            field=models.CharField(default='', max_length=200, verbose_name='Nombre de programa'),
        ),
    ]
