# Generated by Django 4.2.27 on 2026-02-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0004_remove_visitainterna_nombre_ficha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitainterna',
            name='observaciones',
            field=models.TextField(blank=True, default='', verbose_name='Observaciones'),
        ),
    ]
