# Generated by Django 4.2.27 on 2026-02-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0005_visitainterna_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitainterna',
            name='tipo_documento_responsable',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PPT', 'Permiso Especial de Permanencia'), ('PP', 'Pasaporte')], default='0', max_length=3, verbose_name='Tipo de Documento del responsable'),
            preserve_default=False,
        ),
    ]
