# Generated by Django 6.0.2 on 2026-02-13 17:33

import visitaInterna.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0008_visitainterna_token_acceso_asistentevisitainterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='documento_adicional',
            field=models.FileField(blank=True, null=True, upload_to=visitaInterna.models.documento_asistente_path_interna, verbose_name='Documento Adicional (Opcional)'),
        ),
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to=visitaInterna.models.documento_asistente_path_interna, verbose_name='Documento de Identidad (PDF/Imagen)'),
        ),
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='estado',
            field=models.CharField(choices=[('pendiente_documentos', 'Pendiente de revisión de documentos'), ('documentos_aprobados', 'Documentos aprobados'), ('documentos_rechazados', 'Documentos rechazados')], default='pendiente_documentos', max_length=25, verbose_name='Estado de documentos'),
        ),
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='observaciones_revision',
            field=models.TextField(blank=True, verbose_name='Observaciones de revisión'),
        ),
    ]
