# Generated by Django 6.0.2 on 2026-02-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0010_visitainterna_fecha_solicitud_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnvioCoordinacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_destino', models.EmailField(max_length=254, verbose_name='Correo destino')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('estado_resultado', models.CharField(choices=[('enviado', 'Enviado exitosamente'), ('fallido', 'Fallo en envío')], default='enviado', max_length=20, verbose_name='Estado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('usuario_remitente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Remitente')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_coordinacion', to='visitaInterna.visitainterna', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Registro de Envío a Coordinación',
                'verbose_name_plural': 'Registros de Envíos a Coordinación',
                'ordering': ['-fecha_envio'],
            },
        ),
    ]
