# Generated by Django 6.0.2 on 2026-02-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0012_alter_visitainterna_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitainterna',
            name='fecha_visita',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de la visita'),
        ),
        migrations.AddField(
            model_name='visitainterna',
            name='hora_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AddField(
            model_name='visitainterna',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de inicio'),
        ),
    ]
