# Generated by Django 6.0.2 on 2026-02-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0014_asistentevisitainterna_email_qr_enviado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='es_reutilizado',
            field=models.BooleanField(default=False, verbose_name='Es una copia de un asistente anterior'),
        ),
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='puede_reutilizar',
            field=models.BooleanField(default=True, verbose_name='Puede reutilizarse en futuras visitas'),
        ),
        migrations.AddField(
            model_name='asistentevisitainterna',
            name='visita_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias', to='visitaInterna.asistentevisitainterna', verbose_name='Asistente original (si es reutilizado)'),
        ),
    ]
