# Generated by Django 6.0.2 on 2026-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0015_asistentevisitainterna_es_reutilizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitainterna',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
