# Generated by Django 6.0.3 on 2026-03-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0015_asistentevisitainterna_es_reutilizado_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asistentevisitainterna',
            table='asistente_visita_interna',
        ),
        migrations.AlterModelTable(
            name='historialaccionvisitainterna',
            table='historial_accion_visita_interna',
        ),
        migrations.AlterModelTable(
            name='visitainterna',
            table='visita_interna',
        ),
    ]
