# Generated by Django 6.0.3 on 2026-03-10 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0016_alter_asistentevisitainterna_table_and_more'),
        ('visitaInterna', '0017_asistentevisitainterna_estado_autorizacion_padres_and_more'),
    ]

    operations = [
    ]
