# Generated by Django 6.0.3 on 2026-03-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0016_alter_visitainterna_observaciones'),
        ('visitaInterna', '0018_merge_20260310_0858'),
    ]

    operations = [
    ]
