# Generated by Django 4.2.27 on 2026-02-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0002_alter_visitaexterna_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitaexterna',
            options={'verbose_name': 'Visita Externa', 'verbose_name_plural': 'Visitas Externas'},
        ),
        migrations.RemoveField(
            model_name='visitaexterna',
            name='articulacion',
        ),
        migrations.RemoveField(
            model_name='visitaexterna',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='visitaexterna',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='visitaexterna',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='visitaexterna',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='visitaexterna',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='visitaexterna',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='visitaexterna',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='visitaexterna',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='visitaexterna',
            name='cantidad_visitantes',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Visitantes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitaexterna',
            name='correo_responsable',
            field=models.EmailField(default='Sin especificar', max_length=254, verbose_name='Correo Electrónico del responsable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitaexterna',
            name='nombre_responsable',
            field=models.CharField(default='Sin especificar', max_length=200, verbose_name=' nombre Responsable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitaexterna',
            name='observacion',
            field=models.TextField(blank=True, verbose_name='Observación'),
        ),
        migrations.AddField(
            model_name='visitaexterna',
            name='telefono_responsable',
            field=models.CharField(default=3000000000, max_length=20, verbose_name='Teléfono del responsable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitaexterna',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre de la institución'),
        ),
    ]
