# Generated by Django 4.2.27 on 2026-02-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0003_alter_visitaexterna_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitaexterna',
            name='documento_responsable',
            field=models.CharField(default=0, max_length=50, verbose_name='Documento del responsable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitaexterna',
            name='tipo_documento_responsable',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PPT', 'Permiso Especial de Permanencia'), ('PP', 'Pasaporte')], default='0', max_length=3, verbose_name='Tipo de Documento del responsable'),
            preserve_default=False,
        ),
    ]
