# Generated by Django 6.0.2 on 2026-02-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0004_visitaexterna_documento_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitaexterna',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
