# Generated by Django 6.0.2 on 2026-02-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0005_visitaexterna_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitaexterna',
            name='token_acceso',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Token de acceso'),
        ),
        migrations.CreateModel(
            name='AsistenteVisitaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('TI', 'Tarjeta de Identidad'), ('PPT', 'Permiso Especial de Permanencia'), ('PP', 'Pasaporte')], max_length=3, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistentes', to='visitaExterna.visitaexterna', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Asistente de Visita Externa',
                'verbose_name_plural': 'Asistentes de Visitas Externas',
                'ordering': ['nombre_completo'],
                'unique_together': {('visita', 'numero_documento')},
            },
        ),
    ]
