# Generated by Django 6.0.2 on 2026-02-15 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0007_asistentevisitaexterna_documento_adicional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitaexterna',
            name='fecha_solicitud',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='visitaexterna',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('enviada_coordinacion', 'Enviada a coordinación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='HistorialAccionVisitaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('creacion', 'Solicitud creada'), ('ver_detalle', 'Detalle visualizado'), ('envio_coordinacion', 'Enviada a coordinación'), ('aprobacion', 'Visita aprobada'), ('rechazo', 'Visita rechazada'), ('notificacion', 'Notificación enviada'), ('modificacion', 'Datos modificados')], max_length=20, verbose_name='Tipo de acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='visitaExterna.visitaexterna', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Historial de Acción',
                'verbose_name_plural': 'Historial de Acciones',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
