# Generated by Django 6.0.2 on 2026-02-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0008_visitaexterna_fecha_solicitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaexterna',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('enviada_coordinacion', 'Enviada a coordinación'), ('aprobada_inicial', 'Aprobada - Registro de asistentes habilitado'), ('documentos_enviados', 'Documentos enviados - Pendiente revisión'), ('en_revision_documentos', 'En revisión de documentos'), ('confirmada', 'Visita Confirmada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=25, verbose_name='Estado'),
        ),
    ]
