# Generated by Django 6.0.3 on 2026-03-09 21:03

import visitaExterna.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0013_asistentevisitaexterna_es_reutilizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentevisitaexterna',
            name='formato_autorizacion_padres',
            field=models.FileField(blank=True, null=True, upload_to=visitaExterna.models.documento_asistente_path_externa, verbose_name='Formato Autorización Padres de Familia (Requerido para menores de edad)'),
        ),
    ]
