# Generated by Django 6.0.2 on 2026-03-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0013_asistentevisitaexterna_es_reutilizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaexterna',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
