# Generated by Django 6.0.3 on 2026-03-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0014_asistentevisitaexterna_formato_autorizacion_padres'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistentevisitaexterna',
            name='estado_autorizacion_padres',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado Autorización Padres'),
        ),
        migrations.AddField(
            model_name='asistentevisitaexterna',
            name='observaciones_autorizacion_padres',
            field=models.TextField(blank=True, verbose_name='Observaciones Autorización Padres'),
        ),
    ]
