# Generated by Django 6.0.3 on 2026-03-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0014_alter_asistentevisitaexterna_table_and_more'),
        ('visitaExterna', '0015_asistentevisitaexterna_estado_autorizacion_padres_and_more'),
    ]

    operations = [
    ]
