# Generated by Django 6.0.2 on 2026-03-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0014_alter_visitaexterna_observacion'),
        ('visitaExterna', '0016_merge_20260310_0900'),
    ]

    operations = [
    ]
