# Generated by Django 6.0.2 on 2026-03-12 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaExterna', '0018_merge_20260312_0844'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitaexterna',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada_coord', 'Aprobada por Coordinador'), ('correccion_docs', 'Requiere Corrección de Documentos'), ('reprogramacion_solicitada', 'Reprogramación Solicitada'), ('rechazada', 'Rechazada'), ('aprobada_final', 'Aprobada Final')], default='pendiente', max_length=25, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='HistorialReprogramacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_anterior', models.DateTimeField(verbose_name='Fecha y hora anterior de la visita')),
                ('motivo', models.TextField(verbose_name='Motivo de la reprogramación')),
                ('tipo', models.CharField(choices=[('coordinador', 'Coordinador'), ('administrador', 'Administrador')], max_length=15, verbose_name='Tipo de solicitud')),
                ('completada', models.BooleanField(default=False, verbose_name='Reprogramación completada')),
                ('fecha_reprogramacion', models.DateTimeField(blank=True, null=True, verbose_name='Nueva fecha y hora de la visita')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reprogramaciones_externas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por')),
                ('visita_externa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprogramaciones_externa', to='visitaExterna.visitaexterna', verbose_name='Visita Externa')),
            ],
            options={
                'verbose_name': 'Historial de Reprogramación',
                'verbose_name_plural': 'Históricos de Reprogramación',
                'db_table': 'historial_reprogramacion_externa',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
