from django.urls import path
from . import views
from . import reprogramacion_views

app_name = "gestion_visitas"

urlpatterns = [
    path("visitas/", views.api_listar_visitas, name="api_listar_visitas"),
    path(
        "visitas/<str:tipo>/<int:visita_id>/",
        views.api_detalle_visita,
        name="api_detalle_visita",
    ),
    path(
        "visitas/<str:tipo>/<int:visita_id>/<str:accion>/",
        views.api_accion_visita,
        name="api_accion_visita",
    ),
    path(
        "asistentes/<str:tipo>/<int:asistente_id>/<str:accion>/",
        views.api_revisar_documento_asistente,
        name="api_revisar_documento_asistente",
    ),
    path(
        "api/autorizacion-padres/<str:tipo>/<int:asistente_id>/<str:accion>/",
        views.api_revisar_autorizacion_padres,
        name="api_revisar_autorizacion_padres",
    ),
    path(
        "visitas-aprobadas/",
        views.api_visitas_aprobadas,
        name="api_visitas_aprobadas",
    ),
    path(
        "documentos-revision/",
        views.api_documentos_revision,
        name="api_documentos_revision",
    ),
    path("api/visitas/", views.api_listar_visitas, name="api_listar_visitas_legacy"),
    path(
        "api/visitas/<str:tipo>/<int:visita_id>/",
        views.api_detalle_visita,
        name="api_detalle_visita_legacy",
    ),
    path(
        "api/visitas/<str:tipo>/<int:visita_id>/<str:accion>/",
        views.api_accion_visita,
        name="api_accion_visita_legacy",
    ),
    path(
        "api/asistentes/<str:tipo>/<int:asistente_id>/<str:accion>/",
        views.api_revisar_documento_asistente,
        name="api_revisar_documento_asistente_legacy",
    ),
    path(
        "api/visitas-aprobadas/",
        views.api_visitas_aprobadas,
        name="api_visitas_aprobadas_legacy",
    ),
    path(
        "api/documentos-revision/",
        views.api_documentos_revision,
        name="api_documentos_revision_legacy",
    ),
    path(
        "reprogramacion/solicitar/<str:tipo>/<int:visita_id>/",
        reprogramacion_views.solicitar_reprogramacion,
        name="solicitar_reprogramacion",
    ),
    path(
        "reprogramacion/completar/<str:tipo>/<int:visita_id>/",
        reprogramacion_views.completar_reprogramacion,
        name="completar_reprogramacion",
    ),
    path(
        "reprogramacion/historial/<str:tipo>/<int:visita_id>/",
        reprogramacion_views.obtener_historial_reprogramaciones,
        name="historial_reprogramacion",
    ),
    path(
        "reprogramacion/pendientes-instructor/",
        reprogramacion_views.obtener_reprogramaciones_pendientes_instructor,
        name="reprogramaciones_pendientes_instructor",
    ),
    path(
        "api/reprogramacion/solicitar/<str:tipo>/<int:visita_id>/",
        reprogramacion_views.solicitar_reprogramacion,
        name="solicitar_reprogramacion_legacy",
    ),
    path(
        "api/reprogramacion/completar/<str:tipo>/<int:visita_id>/",
        reprogramacion_views.completar_reprogramacion,
        name="completar_reprogramacion_legacy",
    ),
    path(
        "api/reprogramacion/historial/<str:tipo>/<int:visita_id>/",
        reprogramacion_views.obtener_historial_reprogramaciones,
        name="historial_reprogramacion_legacy",
    ),
    path(
        "api/reprogramacion/pendientes-instructor/",
        reprogramacion_views.obtener_reprogramaciones_pendientes_instructor,
        name="reprogramaciones_pendientes_instructor_legacy",
    ),
]
