# Generated by Django 4.2.27 on 2026-02-02 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitaInterna', '0002_alter_visitainterna_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitainterna',
            name='cantidad_aprendices',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999999)], verbose_name='Cantidad de aprendices'),
        ),
    ]
