# Generated by Django 4.2.27 on 2026-02-23 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documentos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visitaInterna', '0012_alter_visitainterna_estado'),
        ('visitaExterna', '0010_alter_visitaexterna_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to=documentos.models.documento_upload_path)),
                ('categoria', models.CharField(choices=[('EPP Necesarios', '👷🏻\u200d♂️ EPP Necesarios'), ('Formato Inducción y Reinducción', '📜 Formato Inducción y Reinducción'), ('ATS', '📝 ATS'), ('Formato Auto Reporte Condiciones de Salud', '👩🏻\u200d⚕️ Formato Auto Reporte Condiciones de Salud'), ('Charla de Seguridad y Calestenia', '🤸🏻\u200d♂️ Charla de Seguridad y Calestenia'), ('Formato Autorización Padres de Familia', '📋 Formato Autorización Padres de Familia')], default='EPP Necesarios', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('tamaño', models.PositiveIntegerField(default=0, help_text='Tamaño en bytes')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoSubidoAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=documentos.models.documento_subido_upload_path, verbose_name='Archivo subido')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('asistente_externa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos', to='visitaExterna.asistentevisitaexterna')),
                ('asistente_interna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos', to='visitaInterna.asistentevisitainterna')),
                ('documento_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos', to='documentos.documento', verbose_name='Documento requerido')),
            ],
            options={
                'verbose_name': 'Documento Subido por Asistente',
                'verbose_name_plural': 'Documentos Subidos por Asistentes',
                'ordering': ['documento_requerido__categoria'],
            },
        ),
    ]
