# Generated by Django 6.0.3 on 2026-03-09 14:07

import documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentosubidoasistente_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosubidoasistente',
            name='archivo',
            field=models.FileField(max_length=500, upload_to=documentos.models.documento_subido_upload_path, verbose_name='Archivo subido'),
        ),
    ]
