# Generated by Django 6.0.3 on 2026-03-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documentosubidoasistente_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='documento',
            table='documento',
        ),
        migrations.AlterModelTable(
            name='documentosubidoasistente',
            table='documento_subido_asistente',
        ),
    ]
