# Generated by Django 6.0.3 on 2026-03-10 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_alter_documentosubidoasistente_archivo'),
        ('panel_instructor_interno', '0005_alter_aprendiz_documento_identidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoSubidoAprendiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('observaciones_revision', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(max_length=500, upload_to='documentos_aprendices/%Y/%m/', verbose_name='Archivo subido')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('aprendiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos', to='panel_instructor_interno.aprendiz', verbose_name='Aprendiz')),
                ('documento_requerido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_subidos_aprendices', to='documentos.documento', verbose_name='Documento requerido')),
            ],
            options={
                'verbose_name': 'Documento Subido por Aprendiz',
                'verbose_name_plural': 'Documentos Subidos por Aprendices',
                'ordering': ['-fecha_subida'],
                'unique_together': {('aprendiz', 'documento_requerido')},
            },
        ),
    ]
