# Generated by Django 6.0.3 on 2026-03-11 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documentosubidoaprendiz'),
        ('documentos', '0004_merge_20260310_0741'),
    ]

    operations = [
    ]
