# Generated by Django 6.0.3 on 2026-03-10 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_perfilusuario_aprobado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='fecha_aprobacion',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='razon_rechazo',
        ),
        migrations.AlterModelTable(
            name='perfilusuario',
            table='perfil_usuario',
        ),
    ]
